### PR TITLE
chore:create one image dir and change path to some images

### PR DESCRIPTION
**Pull request by Gasorekibo**
- [x] Created one image folder and moved all images.
- [x] Change the path for some images

### CODE REVIEW

**Review by christelle-gihozo — CHANGES_REQUESTED** [review]
Weren't the images supposed to be all in the src directory? I thought you would move them from the src/sections/img to src/img but if this works to it's fine

**Comment by Gasorekibo** [comment]
> Weren't the images supposed to be all in the src directory? I thought you would move them from the src/sections/img to src/img but if this works to it's fine

Yes, that would also be another option, but I checked where we had many images to reduce the workload.

**Review by AdelineA — APPROVED** [review]
Good

**Comment by AdelineA** [comment]
> Weren't the images supposed to be all in the src directory? I thought you would move them from the src/sections/img to src/img but if this works to it's fine


Let's leave this for now, we can do that for the QA reviews

**Pull request merged**
