### PR TITLE
fix:fix imprint navigation

### PR DESCRIPTION
**Pull request by Gasorekibo**
This PR does the following:

1. Make Language links unfixed on the top on small Screens.
2. Change the background of Baumeister on the scroll
lang

### CODE REVIEW

**Review by brendahuwitonze — APPROVED** [review]
It looks like everything is good

**Review by christelle-gihozo — CHANGES_REQUESTED** [review]
The remaining thing is sorting the classes, good job!

**Comment by Gasorekibo** [comment]
> The remaining thing is sorting the classes, good job!

done.

**Review by Kevin-gram — APPROVED** [review]
This is okay

**Comment by Gasorekibo** [comment]
> This is okay

Alright

**Pull request merged**
