### PR TITLE
Ft/data privacy

### PR DESCRIPTION
**Pull request by Gasorekibo**
- [x] Add Text on sm screen
- [x] Responsive on md screen
- [x] Responsive on lg screen
privacy-md
privacy-sm
privacy-lg

### CODE REVIEW

**Comment by Kevin-gram** [comment]
this page has conflicts

**Comment by Kevin-gram** [comment]
check it out

**Review by Kevin-gram — CHANGES_REQUESTED** [review]
there  are some conflicts

**Comment by Gasorekibo** [comment]
> there are some conflicts

Conflict solved

**Pull request merged**
