### PR TITLE
feat: adding custom fonts

### PR DESCRIPTION
**Pull request by Kevin-gram**
Added fonts and colors

### CODE REVIEW

**Review by Gasorekibo — APPROVED** [review]
Everything is perfect.

**Review by peninah98 — APPROVED** [review]
It seems good to me! But the next pull request you should consider making a good pull request descriptions, to give a reviewer a good and a clear picture of what you have implemented in that pull request.

**Review by peninah98 — CHANGES_REQUESTED** [review]
Your branch has conflicts, resolve them.

**Review by peninah98 — APPROVED** [review]
LGTM

**Comment by peninah98** [comment]
Merged!

**Pull request merged**
